
TILE_SIZE = 17
SCALE_FACTOR_HEIGHT = 35
WINDOW_WIDTH = TILE_SIZE * 59
WINDOW_NAME = "scene"
WINDOW_HEIGHT = TILE_SIZE * SCALE_FACTOR_HEIGHT

#Tile size determines everything else

LEVEL_MAP_FILENAME = "level0_map"
#assumes you name them 
TILE_IMAGE_DIRECTORY = "./img/tile/"
BACKGROUND_IMAGES_DIRECTORY = "./img/background/"
TILE_TYPES = 21

BG_IMAGE_COORDINATES = [
    (0, 0),
    (0, WINDOW_HEIGHT - 254 - 300),
    (0, WINDOW_HEIGHT - 296 - 150),
    (0, WINDOW_HEIGHT - 398)
]



# Calculate adjusted dimensions for the tile map
#TILE_MAP_SCREEN_HEIGHT should TILE_SIZE * scale_factor and Factor should 
#be less than WINDOW_HEIGHT's scale_factor
TILE_MAP_SCREEN_HEIGHT = TILE_SIZE * (SCALE_FACTOR_HEIGHT - (SCALE_FACTOR_HEIGHT // 3))
TILE_MAP_SCREEN_WIDTH = WINDOW_WIDTH
TILE_MAP_FULL_HEIGHT = TILE_MAP_SCREEN_HEIGHT
TILE_MAP_FULL_WIDTH = TILE_MAP_SCREEN_WIDTH * 3


TILE_MAP_FULL_ROWS = TILE_MAP_FULL_HEIGHT // TILE_SIZE
TILE_MAP_FULL_COLS = TILE_MAP_FULL_WIDTH // TILE_SIZE


# Calculate the number of rows and columns based on adjusted dimensions
TILE_MAP_SCREEN_ROWS = TILE_MAP_SCREEN_HEIGHT // TILE_SIZE
TILE_MAP_SCREEN_COLS = WINDOW_WIDTH // TILE_SIZE


#tile menu constants
TILE_MENU_YLOC = TILE_MAP_SCREEN_HEIGHT + 30
TILES_DISPLAYED_NUM = 10
TILE_MENU_BTN_SPACING = 30
TILE_MENU_SPACE_NUM = 9
TILE_MENU_OFFSET_X = (TILE_MAP_SCREEN_WIDTH // 2) - (((TILES_DISPLAYED_NUM * TILE_SIZE) + (TILE_MENU_BTN_SPACING * TILE_MENU_SPACE_NUM)) // 2)



# Other constants based on TILE_SIZE

SCROLL_AMOUNT = TILE_SIZE

#SAVE BTN
SAVE_BTN_X = (WINDOW_WIDTH // 2) - 65
SAVE_BTN_Y = TILE_MENU_YLOC + 60

#LOAD BTN
LOAD_BTN_X = SAVE_BTN_X + 100
LOAD_BTN_Y = TILE_MENU_YLOC + 60


#EVENT NAMES
SCROLL_ACTION = "scroll"
RECT_BORDER_ACTION = "rect"
TILE_MENU_SCROLL_LEFT = "tile_menu_scroll_left"
TILE_MENU_SCROLL_RIGHT = "tile_menu_scroll_right"


LIGHT_BLUE = (255, 224, 130)

